### ISSUE TITLE
Cosmetic issue / browser navbar

### ISSUE THREAD

**Issue by twiddern** [TheInsomniac/Nginx-Fancyindex-Theme#3]
I've there one more cosmetic issue with the indexer
![sc](https://cloud.githubusercontent.com/assets/2402659/3059775/a334aada-e1ef-11e3-8618-da10b6fcc45c.PNG)

As you can see I've got navbars on both sides. Even in fullscreen mode with my Mozilla Browser. May you can have a look into that.

// I've just updated the screenshot and scrolled to the end. You'll see that the table is not well formed

**Comment by TheInsomniac** [comment]
Your file listing is wider than the viewport but I can’t reason why. I just tested with Safari 7, Chrome 36, and Firefox 31 and in every instance the #list was constrained within the .box-content. #list is 100% width but does have 20px of padding on all sides.

What version of Firefox are you using and on what OS?

If you know your way around CSS perhaps you could try changing:

```
.box .box-content {
  /* padding: 20px; */
  background: #fff;
  /* width: 100%; */
  width: 97%;
  margin: 20px auto;
}
```

**Comment by twiddern** [comment]
I'm stuck on Cyberfox (Firefox 28 derivate for Windows x64) 28.0.1 with a Windows 8.1

**Comment by TheInsomniac** [comment]
Confirmed on an old XP box running FF 20! 

Pushed the changes.. 

Please close if this fixes your issue.

**Comment by twiddern** [comment]
The horizontal navbar is gone with the changes in the .css but the vertical navbar still appears for some reasons 
![sna](https://cloud.githubusercontent.com/assets/2402659/3060130/8c8c01b6-e1f4-11e3-9fd7-efabbc3432d1.PNG)
